language: node_js
node_js:
- '5.8'
before_script:
- npm install -g webpack
- npm install -g karma-cli
- npm install -g jasmine
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
deploy:
  matrix:
  - provider: s3
  - provider: codedeploy
    bucket: crunchytunes
    key: crunchy-tunes.zip
    application: crunchy-tunes
    deployment_group: crunchy-tunes-dep-group
    region: us-west-2
    wait-until-deployed: true
    on:
      branch: travis-aws-deploy
    secret_access_key:
      secure: Hl3qQ444+q1zZ2btcVr6Yk//IezPUgsDFgloAxrrKH3OZ05jX+lFm5j+nm12t14K+C4O/NDxlZ83iYT9sF+yqH5MQZffnuQBX2Amg5oCkNxkX9bR0/gNxFc890Hmuxs7VJ7JsRbfwIu8C5VJp9yZc+/x72fW01ctsAvyhChr3xqDuVBpcdwpbCMGV+/+tJmMpjZB5K7tUOjaIWK8Gyiv2Z5hZTa5s88sBSMQBneDf2rE9jW50Ccse9s6TlI6ZggMwQBW4e/w+Uxzjb/suTDBRH4LwKbo65K0fYIU2YaWNSoV8moQZTK9kKSwCCzFimRNonzTF1FAkDDoy2j/xWLbC6VhJGCyqdmQhnSWfnJZiWRSTmMgexLYUeuYQ5P0Wqh3RqP+gY2ewM9myfXR61k9sjxNW0mylgFacypuiW4QkTLk0uONDyF2n0GOD3Y0jA7PYjO4yzoshDHGQmd2oXR6AliMBMyevT6CdblrStKC/blpZ4IRsO9pwDIhSTtuOp7tLniQJDUHkGmvVVPAi943RgkHWEHgA8f9mo0QZfVqDYiuvQgKgLxRSnVoubBpLVSePSV71SJA/Ju6/38XiChJdlYuis86JailQsY3562wZ7aKTvQ29ffGraNjp3eLmWMtFKDBd4kr60Kc5AMn4DqtKywdQyfGJlTIWgol61BMWLc=
    access_key_id:
      secure: m0MSvf51U8x86S8LMCRnvmGM2RcIlab0GSyYbXV4yFr+EiY9z7QKlNSdTMNpSywo0hfZcuRc0UMxUuY+T3NjkMsqaB9FK3OO+21vAHLEXGqpBAoRm3rKGu/Nkccq3/1TkxY08/Zsf4D3D1ODuKUU+U099pLPtw8YJFtuHeZvhPPllK1POjtA3YwfacObDPELvk45sgw1a/Os4QJ2090WIqcl1A9oS301F3dOusZb4RExnQ/ZN6UyUX//dvdV05mxoPKryXvsTmIb74T3ykA9oxRasDyW4qgQ0vOtMjg7lXwQxkBsjPJl0UbfLvjO+3OJtKjF8FeMK+ZtNls9YW97dX1hP2PAXgiN/ClHTxDTGzRLC6RydVgyMLszuKA27/S8Q6o2rnsf01hwlpUhKnUczdUcVfXAKNAVfQyEEGmpJ5CXF0FODbyiBiIQG1v+IQ3C0SvdIwfjdmMLs1I5raQw2lPciPgX0cK2yBDFb/yMPpWEmuHT8jTSz3dMtkWC4/l4h8W8YYSqugOTbfu4vbNKtSOQIAX+Y4aDQsHTA6JjOa7AhV+Gb47dajdpsvp56Z/PfRyu6fMSN8KbsQA3SQMCjMKZ3WkkMlmLL7nSJk3U5vcXyJFbLDrwOYocOeqnBwgqZh16+UNrGFSaxFIEejps33lL/eDbXzh+Lw08zBc3YUM=
